version: '3'
services:
  odoo-TENANT_NAME:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "PORT_NUMBER:8069"
      - "HTTPS_PORT:8071"
      - "CHAT_PORT:8072"
    volumes:
      - odoo-TENANT_NAME-data:/var/lib/odoo
      - /opt/odoo-addons/shared:/mnt/shared-addons
      - /opt/odoo-addons/tenant-specific/TENANT_NAME:/mnt/extra-addons
    environment:
      - HOST=${POSTGRES_HOST:-192.168.60.110}
      - PORT=${POSTGRES_PORT:-5432}
      - USER=${POSTGRES_USER:-odoo}
      - PASSWORD=${POSTGRES_PASSWORD} 
      - DB_NAME=DB_NAME
      - VIRTUAL_HOST=TENANT_NAME.arcweb.com.au
      - VIRTUAL_PORT=8069
      - PGSSLMODE=prefer
      - DB_MAXCONN=2
    command: ["odoo", "--without-demo=all", "--workers=2", "--proxy-mode", "--max-cron-threads=1"]
    restart: always
    networks:
      - odoo-network
      - nginx-network

volumes:
  odoo-TENANT_NAME-data:

networks:
  odoo-network:
    internal: true
  nginx-network:
    external: true
